FROM mysql@sha256:dce31fcdd15aaedb5591aa89f19ec37cb79981af46511781fa41287d88ed0abd

ENV TZ=UTC \
  MYSQL_DATABASE=cuicin \
  MYSQL_USER=cuicin \
  MYSQL_PASSWORD=cuicin1234 \
  MYSQL_ROOT_PASSWORD=cuicin1234

COPY ./my.cnf /etc/my.cnf
